spring.application.name=social-network-backend
server.port=8080

# Read Neo4j connection details from environment variables
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}
